# Generated by Django 4.2.4 on 2023-09-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_second_name_customer_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'SMALL'), ('M', 'MEDIUM'), ('XL', 'XLARGE'), ('XXL', 'XXLARGE'), ('OS', 'OS')], default='OS', max_length=7, null=True),
        ),
    ]
