# Generated by Django 4.2.4 on 2023-09-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_item_slug_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='care_instructions',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
