# Generated by Django 4.2.4 on 2023-09-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_itemvariant_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariant',
            name='size',
            field=models.CharField(blank=True, choices=[('SMALL', 'SMALL'), ('MEDIUM', 'MEDIUM'), ('XLARGE', 'XLARGE'), ('LARGE', 'LARGE'), ('XXLARGE', 'XXLARGE'), ('OS', 'OS')], default='OS', max_length=7, null=True),
        ),
    ]
