# Generated by Django 4.2.4 on 2023-09-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_addres_address_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
