# Generated by Django 4.2.4 on 2023-09-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_itemvariant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariant',
            name='name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=7),
        ),
    ]
